version: "3"
services:
  config-manager-app:
    build: .
    image: config-manager
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/cloudconfig?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
 
  mysqldb:
    image: mysql:8
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=cloudconfig  
